In [1]:
import numpy as np

Create numpy array

In [2]:
a = np.array([1,3,5,2,6,4])

In [3]:
print(a)  

[1 3 5 2 6 4]


In [4]:
b = np.array([[1,5,7,19,2],[2,4,3,34,27]])
print(b)

[[ 1  5  7 19  2]
 [ 2  4  3 34 27]]


In [5]:
c = np.array([1.2,5.9])

In [6]:
a.ndim #Get Dimenion

1

In [7]:
b.ndim

2

In [8]:
a.shape #Get Shape

(6,)

In [9]:
b.shape

(2, 5)

In [10]:
a.dtype #data type of array 

dtype('int32')

In [11]:
c.dtype

dtype('float64')

In [12]:
a.itemsize #number of bytes of array "size of data type"

4

In [13]:
c.itemsize

8

In [14]:
a.size #number of element 

6

In [15]:
b.size

10

In [16]:
a.nbytes # a.size * a.itemsize

24

In [17]:
b.nbytes

40

In [18]:
#[r,c] 
b[1,3] #access to specific element

34

In [19]:
a[-4] #access from the end

5

In [20]:
b[1,:] # Get specific row 

array([ 2,  4,  3, 34, 27])

In [21]:
b[:,3] # Get specific column

array([19, 34])

In [22]:
b[0,0:3:3]

array([1])

In [23]:
b[0,0:5:2]

array([1, 7, 2])

In [24]:
b[0,0:5:4]

array([1, 2])

In [25]:
b[0,2:5:5]

array([7])

In [26]:
b[0,1:3:2]

array([5])

In [27]:
a[2]=40 # replace value in array
print(a)

[ 1  3 40  2  6  4]


In [28]:
b[:,3]=[50,60] # replace column in array
print(b)

[[ 1  5  7 50  2]
 [ 2  4  3 60 27]]


In [29]:
b[1,:]=[3,5,17,22,30] #replace row in array
print(b)

[[ 1  5  7 50  2]
 [ 3  5 17 22 30]]


=> 3D array

In [30]:
d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[17,18,19]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [17 18 19]]]


In [31]:
d.shape

(2, 3, 3)

In [32]:
d[0,2,2] # access to specific element in 3D array

9

In [33]:
d[:,1,:]

array([[ 4,  5,  6],
       [13, 14, 15]])

In [34]:
d[0,2,2]=20

In [35]:
print(d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8 20]]

 [[10 11 12]
  [13 14 15]
  [17 18 19]]]


Initialize different types of arrays

In [36]:
#All 0s matrix
zero = np.zeros(4)
print(zero)

[0. 0. 0. 0.]


In [37]:
zeros = np.zeros((3,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [38]:
zeros3 = np.zeros((2,3,4))
print(zeros3)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [39]:
#All 1s matrix
one = np.ones(3)
print(one)

[1. 1. 1.]


In [40]:
oneInt = np.ones(4,dtype='int32') #identify data type
print(oneInt)

[1 1 1 1]


In [41]:
onesInt = np.ones((3,2,4),dtype='int32')
print(onesInt)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


In [42]:
#Any other number
#                (r,c),numbers
anyNum = np.full((3,5),20)
print(anyNum)

[[20 20 20 20 20]
 [20 20 20 20 20]
 [20 20 20 20 20]]


In [43]:
anyNum2 = np.full((2,4),((1,3,4,5),(6,9,7,8)))
print(anyNum2)

[[1 3 4 5]
 [6 9 7 8]]


In [44]:
#Any other number (full_like)
anyNumFL = np.full_like(d,5)
print(anyNumFL)

[[[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]]


In [45]:
#Random numbers
np.random.rand(2,4)

array([[0.01862478, 0.00832535, 0.42751269, 0.83551021],
       [0.93593261, 0.47867977, 0.12234054, 0.1341889 ]])

In [46]:
np.random.rand(5)

array([0.62330654, 0.39133045, 0.46852667, 0.5447437 , 0.81320497])

In [47]:
np.random.random(4)

array([0.65088619, 0.55197326, 0.31932138, 0.49003287])

In [48]:
np.random.randn(5) #Positive and negative random numbers

array([ 0.99110556,  0.70540289,  1.2232644 , -0.86775103,  1.34276939])

In [49]:
np.random.randint(1,100) #integer random number between (1,100)

49

In [50]:
np.random.randint(3,50,5) #integer random number between (3,50) in 1D array "size = 5"

array([12, 44, 16, 42, 31])

In [51]:
np.random.randint(30,100,(2,3))

array([[72, 60, 47],
       [84, 57, 79]])

In [52]:
np.random.randint((20,30)) # 2 integer random number the first between (0,20) and the secound between(0,30)

array([19, 21])

In [53]:
np.random.randint(10,size=(3,3))

array([[8, 2, 4],
       [4, 1, 4],
       [9, 8, 1]])

In [54]:
np.random.randint(-10,10,size=(3,3))

array([[-7,  6,  6],
       [ 2, -1,  2],
       [ 1,  5, -5]])

In [55]:
np.random.random((2,3)) # random 2D array

array([[0.9176268 , 0.30585584, 0.09761263],
       [0.22453933, 0.28338599, 0.46547215]])

In [56]:
np.arange(1,10) # Sequence number from 1 to 9

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.random.random_sample(a.shape)

array([0.18840733, 0.59352514, 0.44593946, 0.78758118, 0.50923537,
       0.47634971])

In [58]:
np.random.random_sample(b.shape)

array([[0.09806703, 0.54412885, 0.76471595, 0.55050913, 0.36284247],
       [0.42673393, 0.50033309, 0.62203139, 0.20935818, 0.45522971]])

In [59]:
np.identity(3) #Unit matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
r1 = np.repeat(a,3)
print(r1)

[ 1  1  1  3  3  3 40 40 40  2  2  2  6  6  6  4  4  4]


In [62]:
r2 = np.repeat(b,3,axis=0)
print(r2)

[[ 1  5  7 50  2]
 [ 1  5  7 50  2]
 [ 1  5  7 50  2]
 [ 3  5 17 22 30]
 [ 3  5 17 22 30]
 [ 3  5 17 22 30]]


In [63]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [64]:
#array copy
e=a.copy()
print(e)
e[3]=50
print(e)
print(a)

[ 1  3 40  2  6  4]
[ 1  3 40 50  6  4]
[ 1  3 40  2  6  4]


Mathemtics

In [65]:
print(a)


[ 1  3 40  2  6  4]


In [66]:
a+2

array([ 3,  5, 42,  4,  8,  6])

In [67]:
a-2

array([-1,  1, 38,  0,  4,  2])

In [68]:
a*3

array([  3,   9, 120,   6,  18,  12])

In [69]:
a/4

array([ 0.25,  0.75, 10.  ,  0.5 ,  1.5 ,  1.  ])

In [70]:
f = np.array([1,2,3,4,5,6])
a+f

array([ 2,  5, 43,  6, 11, 10])

In [71]:
a**2

array([   1,    9, 1600,    4,   36,   16], dtype=int32)

In [72]:
#Take the sin
np.sin(a)

array([ 0.84147098,  0.14112001,  0.74511316,  0.90929743, -0.2794155 ,
       -0.7568025 ])

In [73]:
#Take the cos
np.cos(a)

array([ 0.54030231, -0.9899925 , -0.66693806, -0.41614684,  0.96017029,
       -0.65364362])

In [74]:
#Take the tan
np.tan(a)

array([ 1.55740772, -0.14254654, -1.11721493, -2.18503986, -0.29100619,
        1.15782128])

Linear Algebra

In [75]:
g = np.full((2,3),3)
print(g)

h = np.full((3,2), 4)
print(h)

np.matmul(g,h) #Matrix multiplication

[[3 3 3]
 [3 3 3]]
[[4 4]
 [4 4]
 [4 4]]


array([[36, 36],
       [36, 36]])

In [76]:
#find the determinant
i = np.identity(3)
np.linalg.det(i)

1.0

In [77]:
j=np.full((2,2),[[2,3],[4,5]])
np.linalg.det(j)

-2.0

Statistics

In [78]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
stats.ndim

2

In [80]:
np.max(stats)

6

In [81]:
np.max(stats, axis=1)

array([3, 6])

In [82]:
np.min(stats)

1

In [83]:
np.min(stats,axis=1)

array([1, 4])

In [84]:
np.sum(stats) #Sum all the elements of the array

21

In [85]:
np.sum(stats, axis=0) #Add the elements of the row0 and the elements of the row1 of the matrix

array([5, 7, 9])

Reorganizing Arrays

In [86]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [87]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [88]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [89]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [90]:
np.vstack([v2,v2,v1,v2])

array([[5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [91]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [92]:
np.hstack((h1,h2,h1))

array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.]])

Miscellaneous


Load Data from File

In [93]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[13 36 17 56 11  8  2 59 63 90]
 [88 42 77 47 79 32 31 42 91 60]
 [61 68 97 45 15 32 70 18  3 97]]


Boolean Masking and Advanced Indexing

In [94]:
filedata>50

array([[False, False, False,  True, False, False, False,  True,  True,
         True],
       [ True, False,  True, False,  True, False, False, False,  True,
         True],
       [ True,  True,  True, False, False, False,  True, False, False,
         True]])

In [95]:
filedata[filedata>50]

array([56, 59, 63, 90, 88, 77, 79, 91, 60, 61, 68, 97, 70, 97])

In [96]:
np.any(filedata > 50 ,axis=0)

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True])